name: foodgram CI

on:
  push:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install flake8 isort==5.* pytest
          pip install -r backend/requirements.txt

      - name: Lint
        run: |
          flake8 backend
          isort --check-only --diff backend

      - name: Tests
        run: pytest

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/foodgram-backend:latest
          secrets: |
            "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}"
            "DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}"
